name: Publish PDF
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build -t my_resume .
      - name: Run Docker Container
        run: docker run --name my_resume_container my_resume
      - name: Copy PDF from Docker Container
        run: docker cp my_resume_container:/app/main.pdf .
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          force_orphan: true
